name: Issues trigger
on:
    issues:
        types: [opened, closed]
jobs:
    label_issue:
        runs-on: ubuntu-latest
        steps:
            - name: List the issue
              run: echo "${{ toJson(github.event.issue.html_url) }}"